# Generated by Django 6.0 on 2025-12-24 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_user_address_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('picture', models.CharField(max_length=200)),
                ('cuisine', models.CharField(max_length=200)),
                ('raing', models.FloatField()),
            ],
        ),
    ]
