# Generated by Django 6.0 on 2025-12-24 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='raing',
            new_name='rating',
        ),
    ]
